# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Automation Test Execution 
on:
  workflow_dispatch:
  push:
    branches: [ main, dev ]
    
jobs:
  tests:
    name: Cucumber features execution
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code from repository
      uses: actions/checkout@v4
      
    - name: Setting up Node.js 22
      uses: actions/setup-node@v4
      with:
        node-version: 22
        cache: 'npm'
        
    - name: Install dependencies    
      run: npm ci
      
    - name: Test execution
      run: npm run test:tags "@regression"
      
    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: test-results  
        
    - name: Generating cucumber report
      if: always()
      run: |
        echo "Checking for the cucumber report..."
        ls /cucumber.html || echo "No cucumber report generated."
      
    - name: Upload Cucumber report
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: cucumber-report
        path: "**/cucumber.html"

